package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2012-12-22T06:41:01.923-05:00
 * Generated source version: 2.7.1
 * 
 */
@WebServiceClient(name = "PackWS", 
                  wsdlLocation = "http://10.0.1.32:49232/PackWS.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class PackWS extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "PackWS");
    public final static QName PackWSSoap = new QName("http://tempuri.org/", "PackWSSoap");
    public final static QName PackWSSoap12 = new QName("http://tempuri.org/", "PackWSSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://10.0.1.32:49232/PackWS.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PackWS.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.0.1.32:49232/PackWS.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PackWS(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PackWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PackWS() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns PackWSSoap
     */
    @WebEndpoint(name = "PackWSSoap")
    public PackWSSoap getPackWSSoap() {
        return super.getPort(PackWSSoap, PackWSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PackWSSoap
     */
    @WebEndpoint(name = "PackWSSoap")
    public PackWSSoap getPackWSSoap(WebServiceFeature... features) {
        return super.getPort(PackWSSoap, PackWSSoap.class, features);
    }
    /**
     *
     * @return
     *     returns PackWSSoap
     */
    @WebEndpoint(name = "PackWSSoap12")
    public PackWSSoap getPackWSSoap12() {
        return super.getPort(PackWSSoap12, PackWSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PackWSSoap
     */
    @WebEndpoint(name = "PackWSSoap12")
    public PackWSSoap getPackWSSoap12(WebServiceFeature... features) {
        return super.getPort(PackWSSoap12, PackWSSoap.class, features);
    }

}
