
package org.tempuri;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2012-12-22T06:41:01.830-05:00
 * Generated source version: 2.7.1
 * 
 */
public final class PackWSSoap_PackWSSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "PackWS");

    private PackWSSoap_PackWSSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PackWS.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PackWS ss = new PackWS(wsdlURL, SERVICE_NAME);
        PackWSSoap port = ss.getPackWSSoap();  
        
        {
        System.out.println("Invoking getPackage...");
        int _getPackage_id = -699879777;
        org.tempuri.Pack _getPackage__return = port.getPackage(_getPackage_id);
        System.out.println("getPackage.result=" + _getPackage__return);


        }
        {
        System.out.println("Invoking getName...");
        java.lang.String _getName__return = port.getName();
        System.out.println("getName.result=" + _getName__return);


        }
        {
        System.out.println("Invoking addPackage...");
        org.tempuri.Pack _addPackage__package = new org.tempuri.Pack();
        port.addPackage(_addPackage__package);


        }

        System.exit(0);
    }

}
