package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2012-12-22T06:41:01.916-05:00
 * Generated source version: 2.7.1
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "PackWSSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface PackWSSoap {

    @WebResult(name = "getPackageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getPackage", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPackage")
    @WebMethod(action = "http://tempuri.org/getPackage")
    @ResponseWrapper(localName = "getPackageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPackageResponse")
    public org.tempuri.Pack getPackage(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        int id
    );

    @WebResult(name = "getNameResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getName", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetName")
    @WebMethod(action = "http://tempuri.org/getName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetNameResponse")
    public java.lang.String getName();

    @RequestWrapper(localName = "addPackage", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddPackage")
    @WebMethod(action = "http://tempuri.org/addPackage")
    @ResponseWrapper(localName = "addPackageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddPackageResponse")
    public void addPackage(
        @WebParam(name = "package", targetNamespace = "http://tempuri.org/")
        org.tempuri.Pack _package
    );
}
